name: color_generator
description: A flutter package to generate colors
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  solid_lints: ^0.0.16

flutter: