name: Application ON PR DO Code check
on:
  pull_request:
    branches:
      - master
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
          
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml, packages/*/pubspec.yaml"

      - name: Find pubspec.yaml files
        id: find_files
        run: |
          echo "::set-output name=files::$(find . -name pubspec.yaml | tr '\n' ',')"
      
      - name: Setup flutter
        if: steps.check_files.outputs.files_exists == 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Check flutter sdk version
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter --version
      
      - name: Setup Dart Code Metrics
        run: dart pub global activate dart_code_metrics

      - name: Make script executable
        run: chmod +x .github/scripts/analyze_and_test.sh


      - name: Analyze code and run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: .github/scripts/analyze_and_test.sh "${{ steps.find_files.outputs.files }}"
