name: Application ON PR DO Code check
on:
  pull_request:
    branches:
      - master
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
          
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml, packages/*/pubspec.yaml"

      - name: Find pubspec.yaml files
        id: find_files
        run: |
          echo "::set-output name=files::$(find . -name pubspec.yaml | tr '\n' ',')"
          
      - name: Debug check_files output
        run: echo "${{ steps.find_files.outputs.files }}"

      
      - name: Debug check_files output
        run: echo "${{ steps.check_files.outputs.files }}"
